# Generated by Django 4.1.3 on 2022-12-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='image_url',
            field=models.TextField(default='no image'),
        ),
    ]
